export const randomNames = [
    "Bobble Wobble",
    "Fizzlebop McGee",
    "Wacky Wombat",
    "Zippy Zigzag",
    "Jellybean Jester",
    "Noodle Nonsense",
    "Gizmo Giggles",
    "Quirky Quokka",
    "Bingo Bongo",
    "Snazzy Snooze",
    "Tango Twinkle",
    "Pudding Pop",
    "Fluffy Fizz",
    "Merry Mongoose",
    "Jumpy Jamboree",
];
